//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityHistory
    {
        public string ActivityHistoryID { get; set; }
        public string ActivityId { get; set; }
        public string Type { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public string Notes { get; set; }
        public string Location { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ContactGroupIds { get; set; }
        public string ContactIds { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
