//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityContactGroups = new HashSet<ActivityContactGroup>();
            this.ActivityContacts = new HashSet<ActivityContact>();
        }
    
        public string ActivityId { get; set; }
        public string Type { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public string Notes { get; set; }
        public string Location { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool IsFailed { get; set; }
        public Nullable<bool> InititalAlertForActivity { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<ActivityContactGroup> ActivityContactGroups { get; set; }
        public virtual ICollection<ActivityContact> ActivityContacts { get; set; }
    }
}
