//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public string AddressId { get; set; }
        public int AddressTypeId { get; set; }
        public string UserId { get; set; }
        public string AddressText { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public string Telephone { get; set; }
        public string CompanyName { get; set; }
        public string WorkEmail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Mobile { get; set; }
        public string City { get; set; }
    }
}
