//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.Activities = new HashSet<Activity>();
            this.ActivityContactGroups = new HashSet<ActivityContactGroup>();
            this.ActivityContacts = new HashSet<ActivityContact>();
            this.ActivityHistories = new HashSet<ActivityHistory>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.ContactGroups = new HashSet<ContactGroup>();
            this.ContactGroupeds = new HashSet<ContactGrouped>();
            this.ProfileCompletionStatus = new HashSet<ProfileCompletionStatu>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public Nullable<int> SecurityQuestion { get; set; }
        public string RecoveryEmail { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string SSN { get; set; }
        public string MaritalStatus { get; set; }
        public string EducationLevel { get; set; }
        public string EmploymentStatus { get; set; }
        public string ProfilePicture { get; set; }
        public string SecurityAnswer { get; set; }
        public string TimeZoneValue { get; set; }
        public string DateFormat { get; set; }
        public string DateOrder { get; set; }
        public Nullable<int> AlertTimeZone { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int IsUpdated { get; set; }
        public Nullable<bool> IsAccountExpired { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<ActivityContactGroup> ActivityContactGroups { get; set; }
        public virtual ICollection<ActivityContact> ActivityContacts { get; set; }
        public virtual ICollection<ActivityHistory> ActivityHistories { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<ContactGroup> ContactGroups { get; set; }
        public virtual ICollection<ContactGrouped> ContactGroupeds { get; set; }
        public virtual ICollection<ProfileCompletionStatu> ProfileCompletionStatus { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
