//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public string CheckInID { get; set; }
        public string ActivityId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public string Mode { get; set; }
        public Nullable<bool> IsFailed { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
    }
}
