//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInSchedule
    {
        public string CheckInScheduleID { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CurrentCheckIntime { get; set; }
        public Nullable<System.DateTime> NextCheckIntime { get; set; }
        public Nullable<System.DateTime> CheckedInTime { get; set; }
        public Nullable<bool> Ischecked { get; set; }
        public string Mode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IsFailed { get; set; }
        public Nullable<System.DateTime> UTZCurrentCheckInTime { get; set; }
        public Nullable<System.DateTime> UTZNextCheckInTime { get; set; }
        public Nullable<bool> IsUTZUpdated { get; set; }
        public Nullable<bool> RequiredContacts { get; set; }
        public Nullable<bool> InititalAlertForCheckIn { get; set; }
    }
}
