//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactGroupeds = new HashSet<ContactGrouped>();
            this.FinalLetterContacts = new HashSet<FinalLetterContact>();
        }
    
        public string ContactId { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> RelationshipTypeId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsEmergencyContact { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public string ProfilePicture { get; set; }
    
        public virtual ICollection<ContactGrouped> ContactGroupeds { get; set; }
        public virtual ICollection<FinalLetterContact> FinalLetterContacts { get; set; }
    }
}
