//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERRORLOG
    {
        public int Err_LogID { get; set; }
        public string Err_Msg { get; set; }
        public string Formatted_Err_Msg { get; set; }
        public Nullable<int> Err_No { get; set; }
        public Nullable<int> Err_Severity { get; set; }
        public Nullable<int> Err_State { get; set; }
        public Nullable<int> Err_Line { get; set; }
        public string Err_Procedure { get; set; }
    }
}
