//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorTracker
    {
        public long ErrorId { get; set; }
        public string Source { get; set; }
        public string StackTrace { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ErrorTime { get; set; }
        public string InnerException { get; set; }
    }
}
