//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalLetterContact
    {
        public string FinalLetterContactIdc { get; set; }
        public string FinalLetterId { get; set; }
        public string ContactId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public int IsActive { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
