//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlertALifeDBEntities : DbContext
    {
        public AlertALifeDBEntities()
            : base("name=AlertALifeDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<ActivityConactEmailTracking> ActivityConactEmailTrackings { get; set; }
        public DbSet<ActivityContactGroup> ActivityContactGroups { get; set; }
        public DbSet<ActivityContactResponse> ActivityContactResponses { get; set; }
        public DbSet<ActivityContact> ActivityContacts { get; set; }
        public DbSet<ActivityEmailTracking> ActivityEmailTrackings { get; set; }
        public DbSet<ActivityHistory> ActivityHistories { get; set; }
        public DbSet<ActivityResult> ActivityResults { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<AlertFrequency> AlertFrequencies { get; set; }
        public DbSet<Alert> Alerts { get; set; }
        public DbSet<AlertType> AlertTypes { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<CheckIn> CheckIns { get; set; }
        public DbSet<CheckInSchedule> CheckInSchedules { get; set; }
        public DbSet<ContactAccessToken> ContactAccessTokens { get; set; }
        public DbSet<ContactAlertAssociation> ContactAlertAssociations { get; set; }
        public DbSet<ContactGroup> ContactGroups { get; set; }
        public DbSet<ContactGrouped> ContactGroupeds { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<DeathAlert> DeathAlerts { get; set; }
        public DbSet<DeathalertEmailTracking> DeathalertEmailTrackings { get; set; }
        public DbSet<DeathContactEmailTracker> DeathContactEmailTrackers { get; set; }
        public DbSet<DocumentCategory> DocumentCategories { get; set; }
        public DbSet<DocumentCategoryMapping> DocumentCategoryMappings { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<ERRORLOG> ERRORLOGS { get; set; }
        public DbSet<FinalLetter> FinalLetters { get; set; }
        public DbSet<FinalLetterContact> FinalLetterContacts { get; set; }
        public DbSet<FinalLetterDocument> FinalLetterDocuments { get; set; }
        public DbSet<MilestoneMediaFile> MilestoneMediaFiles { get; set; }
        public DbSet<Milestone> Milestones { get; set; }
        public DbSet<ProfilePercentageMaster> ProfilePercentageMasters { get; set; }
        public DbSet<RelationshipType> RelationshipTypes { get; set; }
        public DbSet<RoutineContacResponse> RoutineContacResponses { get; set; }
        public DbSet<RoutineResult> RoutineResults { get; set; }
        public DbSet<SafetyAlert> SafetyAlerts { get; set; }
        public DbSet<SecurityQuestion> SecurityQuestions { get; set; }
        public DbSet<ShortTermAlert> ShortTermAlerts { get; set; }
        public DbSet<SnoozeMaster> SnoozeMasters { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TimeSlatMaster> TimeSlatMasters { get; set; }
        public DbSet<TimeZone> TimeZones { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<TypeMaster> TypeMasters { get; set; }
        public DbSet<UserActivityConfiguraion> UserActivityConfiguraions { get; set; }
        public DbSet<UserAlertConfiguration> UserAlertConfigurations { get; set; }
        public DbSet<Userdefaultconfiguration> Userdefaultconfigurations { get; set; }
        public DbSet<UsersSchedule> UsersSchedules { get; set; }
        public DbSet<WeekdayMaster> WeekdayMasters { get; set; }
        public DbSet<DeathAlertAssociatedInformation> DeathAlertAssociatedInformations { get; set; }
        public DbSet<ErrorTracker> ErrorTrackers { get; set; }
        public DbSet<ProfileCompletionStatu> ProfileCompletionStatus { get; set; }
    }
}
