//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilestoneMediaFile
    {
        public string MilestoneMediaId { get; set; }
        public string MilestoneId { get; set; }
        public string Name { get; set; }
        public string NewName { get; set; }
        public string Extension { get; set; }
        public string Size { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string MediaType { get; set; }
    }
}
