//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilePercentageMaster
    {
        public ProfilePercentageMaster()
        {
            this.ProfileCompletionStatus = new HashSet<ProfileCompletionStatu>();
        }
    
        public string ProfilePercentageMasterId { get; set; }
        public string ProfileMaster { get; set; }
        public int Percentage { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string DisplayText { get; set; }
        public string URL { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        public virtual ICollection<ProfileCompletionStatu> ProfileCompletionStatus { get; set; }
    }
}
