//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafetyAlert
    {
        public string SAlertId { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public Nullable<int> SAIsActive { get; set; }
        public Nullable<System.DateTime> SAStartedDate { get; set; }
        public Nullable<int> SASendInterval { get; set; }
        public Nullable<int> AlertTypeId { get; set; }
        public string SASubject { get; set; }
        public string SAMessage { get; set; }
        public Nullable<int> NRAInterval { get; set; }
        public Nullable<int> NRAQuantity { get; set; }
        public string NRASubject { get; set; }
        public string NRAMessage { get; set; }
        public Nullable<int> CAInterval { get; set; }
        public string CASubject { get; set; }
        public string CAMessage { get; set; }
        public Nullable<int> ContactRelationship { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpComingAlert { get; set; }
    }
}
