//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alertaLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAlertConfiguration
    {
        public string AlertConfigId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> RemindCount { get; set; }
        public Nullable<decimal> RemindintervalValue { get; set; }
        public Nullable<int> ECAlertCount { get; set; }
        public Nullable<decimal> ECAlertintervalValue { get; set; }
        public Nullable<int> AliveconfirmCount { get; set; }
        public Nullable<int> DeadConfirmCount { get; set; }
        public Nullable<int> NotifyDayCount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int IsUpdated { get; set; }
    }
}
